rtl/verilog/mor1kx_dmmu.v
rtl/verilog/mor1kx_immu.v

Xilinx ISE doesn't like defining localparams inside of generate
loops.

Move localparam definition out from generate loops

---

rtl/verilog/mor1kx_lsu_cappuccino.v

This bug was found by ModelSim:
** Error:
mor1kx_lsu_cappuccino.v(249):
(vlog-2730) Undefined variable: 'state'.
** Error:
mor1kx_lsu_cappuccino.v(249):
(vlog-2730) Undefined variable: 'WRITE'.
** Error:
mor1kx_lsu_cappuccino.v(353):
'WRITE' already declared in this scope.
** Error:
mor1kx_lsu_cappuccino.v(357):
'state' already declared in this scope (mor1kx_lsu_cappuccino).

Use variables after they have been defined

---

rtl/verilog/mor1kx_branch_predictor_saturation_counter.v
rtl/verilog/mor1kx_branch_predictor_simple.v

Icarus doesn't handle empty parameter lists

Remove empty parameter lists

---

bench/verilog/mor1kx_monitor.v

I think 'lf.add.s' message is better than 'Unknown opcode 0x32'

Add ORFPX32 commands at monitor trace

---

rtl/verilog/mor1kx_pcu.v

* PCU reset should use non-blocking assignments.
* fix PCU SPR write in generate loop

PCU: fix reset and SPR write

---

rtl/verilog/mor1kx_ctrl_cappuccino.v

This already happens when the PCU submodule is instantiated above.
Curiously, ISE complains but Vivado does not.

Do not assign spr_access_ack[`OR1K_SPR_PC_BASE] twice

---

rtl/verilog/mor1kx_bus_if_wb32.v

The bus interface used to output the interface type at start of
simulation. This was maybe useful for debugging but can be deprecated.

Remove debug parameter output

---

.travis.yml
rtl/verilog/mor1kx-sprs.v
rtl/verilog/mor1kx_branch_prediction.v
rtl/verilog/mor1kx_cfgrs.v
rtl/verilog/mor1kx_cpu_cappuccino.v
rtl/verilog/mor1kx_cpu_espresso.v
rtl/verilog/mor1kx_cpu_prontoespresso.v
rtl/verilog/mor1kx_ctrl_cappuccino.v
rtl/verilog/mor1kx_ctrl_espresso.v
rtl/verilog/mor1kx_ctrl_prontoespresso.v
rtl/verilog/mor1kx_decode.v
rtl/verilog/mor1kx_dmmu.v
rtl/verilog/mor1kx_execute_alu.v
rtl/verilog/mor1kx_fetch_cappuccino.v
rtl/verilog/mor1kx_immu.v
rtl/verilog/mor1kx_lsu_cappuccino.v
rtl/verilog/mor1kx_pic.v
rtl/verilog/mor1kx_rf_cappuccino.v
rtl/verilog/mor1kx_store_buffer.v

Hi,
those are linter fixes based on #44. One topic from there remains: parameter width inference, where I don't see a good solution for now.
I fixed all linter warnings with verilator and travis will check this in future: https://travis-ci.org/openrisc/mor1kx (to be replaced with LibreCores CI).
Cheers,
Stefan

Linter fixes

---

README.md

As discussed in IRC:
```
12:39 < stekern> oetwi_: or1k can only dynamically control addresses to
be cacheable/noncacheable when the mmu is enabled.
12:40 < stekern> mor1kx have an option to work around this, you can
hardwire the upper address space to be noncacheable by adjusting
OPTION_DCACHE_LIMIT_WIDTH
12:42 < stekern> (we should fix the linux kernel to setup some mmu
mapping that marks the uart as non-cacheable before the first early
prints)
```
We have traditionally set cache address width to 31 and mapped devices
into high order address space to avoid caching of device reads and
writes.  Add this as a recommendation in the mor1kx options
documentation.

readme: Update docs on CACHE WIDTH option

---

rtl/verilog/mor1kx_cfgrs.v

The unassigned bits caused undefined values to spread through the design once MMU was enabled

Set unassigned bits in mmucfg SPRs

---

rtl/verilog/mor1kx_true_dpram_sclk.v

Both Synopsys DC and Spyglass lint complain if multiple blocks are used,
even though the code should be functionally identical (at least from my
understanding).

true_dpram: Use a single sequential block

---

README.md

Purpose is to clarify the documentation a bit, and standardize spelling/formatting.
Clarify grammar, fix spelling.
Add links to folders/files.
Slight formatting change.

README: clarify grammar

---

rtl/verilog/mor1kx_rf_cappuccino.v
rtl/verilog/mor1kx_utils.vh

For the  mor1kx defaults the shadow GPR's is set to zero, this is used
when calculating the total register file address size but zero is not
supported.  Fix that by supporting 0.
Also, there is an issue with the expand wire assign when there are no
SHADOW SPRs, don't assign in that case.
This fixes github issue #69.

Utils: Fix zero as a shadow gpr parameter

---

bench/verilog/mor1kx_monitor.v
mor1kx.core
rtl/verilog/mor1kx_cpu.v
rtl/verilog/mor1kx_cpu_marocchino.v
rtl/verilog/mor1kx_top_marocchino.v

This is a WIP to get marocchino working in the or1k-tests suite with mor1kx-generic.  You can see my repos for those.  This compiles now, but still some work to do.
Comments:
- During this integration I found marocchino is almost a complete rewrite of mor1kx.  Should we just separate it out to a new repo i.e. openrisc/marocchino?  This will give it better exposure, and I am not so sure integrating it into mor1kx main will give it the credit it needs.
- The main issues I see with integrating it is:
1. It uses a different wb interconnect (i.e. so there are new signals from WB to the pipeline)
2. It doesnt use the toplevel mor1kx module

Marocchino devel

---

rtl/verilog/mor1kx_cpu_marocchino.v

Previously monitoring was broken because writeback data was not
available when we presented the instrucion to the monitor.  This
meant that the monitor always reported the wrong register values
and result values.
This patch adds some registers to register the insn's and pc's
when then insn is submitted to the order manager, the registers
are then read during writeback.

Marocchino: fixup monitoring to have insn inline with data

---

Jenkinsfile

Create a Jenkinsfile for Librecores CI in mor1kx

---

rtl/verilog/mor1kx_decode.v

Fix mor1kx_decode to accept valid l.fl1 (l.ff1) instructions

---

rtl/verilog/mor1kx_dcache.v
rtl/verilog/mor1kx_immu.v
rtl/verilog/mor1kx_lsu_cappuccino.v

Issue #122
Writing to the tlb rams was dependent on the spr_bus_ack as a means
to only write during the first cycle after a spr_bus_stb_i.  This works
fine for a single write, but if we have a write to itlb_match_spr
followed by itlb_trans_spr the spr_bus_ack never goes low so the write
to itlb_trans_spr is skipped.
Fix this by using the itlb_match_spr_cs_r and itlb_trans_spr_cs_r
signals to control the "first cycle after spr_bus_stb_i" condition. This
way writes can happen independently.
Note, there may still be issues with a write to itlb_match followed by
another write to itlb_match.  Fixing that requires changing the "first
cycle after spr_bus_stb_i" policy, which is similar to dmmu.

Fix issues related to successive mtspr/mtspr instructions

---

rtl/verilog/mor1kx_icache.v

Issue: #127
The reset and error cases override the state to IDLE, we should
check invalidate after this to avoid setting the spr_bus_ack_o
when we are not going to invalidate.
This was detected via formal verification.

icache: Don't allow invalidate on reset or error

---

bench/formal/f_multiclock_op.v
bench/formal/mor1kx_cpu_cappuccino.sby
bench/formal/mor1kx_execute_alu.sby
rtl/verilog/mor1kx_cpu_cappuccino.v
rtl/verilog/mor1kx_execute_alu.v

The previous verification logic counted the cycles it took
to run a multipy operation stopping when it reached 30. then
confirming we were done.  The new logic is a bit more flexible and
simple we count until the operation is complete.  If the count goes
above 32 we fail.  This can be used for any multi clock multiply
operation so we use for 3 stage as well.
In the .sby file I have updated depth to 64 to allow k-indection to
capture a valid start of a multiply operation.  Also, I have changed
task names to be a bit more descriptive.

formal: Update ALU serial operations to time until complete

---

bench/formal/Makefile
bench/formal/fwb_master.v
bench/formal/mor1kx.sby
bench/formal/mor1kx_bus_if_wb32.sby
rtl/verilog/mor1kx.v
rtl/verilog/mor1kx_bus_if_wb32.v
rtl/verilog/mor1kx_cpu_cappuccino.v

Formally verifying properties of "B3_READ_BURSTING"/"B3_REGISTERED_FEEDBACK"  wishbone. Property checks for IBUS_BRIDGE pass, but DBUS_BRIDGE fails in some cases. "CLASSIC" Wishbone is not reset, so many properties of this interface are not satisfied. The maximum request value is set to 16, which can be increased but should choose 'F_LGDEPTH' carefully, or else the test won't pass `f_outstanding` validations.

Formal: Wishbone Interface

---

bench/formal/f_multiclock_op.v
bench/formal/mor1kx_execute_alu.sby
rtl/verilog/mor1kx_execute_alu.v

Previously, the test passed for serial checks of depth 10. We can correctly
validate serial operations only if the solver takes steps more than 40, and proof
should fail if we give depth less than OP_MAX_CLOCKS. Changing assumption
condition on decode_valid_i fixed this.
Also, Multi clock Interface has been used to verify FFL1.

Formal: Update ALU Multiclock Interface

---

mor1kx.core

THis allows us to run the synthesis with different configurations.  For
example:
```
fusesoc run --target synth mor1kx \
--FEATURE_DATACACHE ENABLED \
--FEATURE_DMMU ENABLED \
--OPTION_DCACHE_BLOCK_WIDTH 4 \
--OPTION_DCACHE_LIMIT_WIDTH 31 \
--OPTION_DCACHE_SET_WIDTH 8 \
--OPTION_DCACHE_WAYS 1 \
--FEATURE_INSTRUCTIONCACHE ENABLED \
--FEATURE_IMMU ENABLED \
--OPTION_ICACHE_BLOCK_WIDTH 4 \
--OPTION_ICACHE_LIMIT_WIDTH 31 \
--OPTION_ICACHE_SET_WIDTH 8 \
--OPTION_ICACHE_WAYS 1 \
--OPTION_RF_NUM_SHADOW_GPR 1 \
--FEATURE_ROR ENABLED \
--FEATURE_EXT ENABLED \
--FEATURE_FPU ENABLED > yosys.log ; grep -A10 'Number of cells' yosys.log
INFO: Preparing ::mor1kx:5.0-r3
INFO: Setting up project
INFO: Setting up project
INFO: Building
INFO: Running
Number of cells:              32484
SB_CARRY …
```

core: Add parameters to the synth job

---

rtl/verilog/mor1kx_cpu.v

move include / local parameter calculation to fix verilator compilation issue
error:
```
%Error: /home/hhe07/Documents/openrisc/litex/pythondata-cpu-mor1kx/pythondata_cpu_mor1kx/verilog/rtl/verilog/mor1kx_utils.vh:96:18: Constant function may not be declared under generate (IEEE 1800-2023 13.4.3)
: ... note: In instance 'sim.mor1kx.mor1kx_cpu'
96 | function integer calc_rf_addr_width;
|                  ^~~~~~~~~~~~~~~~~~
/home/hhe07/Documents/openrisc/litex/pythondata-cpu-mor1kx/pythondata_cpu_mor1kx/verilog/rtl/verilog/mor1kx_cpu.v:205:1: ... note: In file included from 'mor1kx_cpu.v'
%Error: /home/hhe07/Documents/openrisc/litex/pythondata-cpu-mor1kx/pythondata_cpu_mor1kx/verilog/rtl/verilog/mor1kx_cpu.v:205:37: Expecting expression to be constant, but can't determine constant for …
```

fix to unbreak verilator compatability

---

.github/workflows/ci.yml
bench/formal/Makefile

Fix issues with formal ci not working
- yosys build is broken
- the formal CI breaks on a few tests, disable those tests

Formal fixups.

---

bench/formal/Makefile
bench/formal/pfpu32_cmp.sby
bench/formal/pfpu32_cmp_snan_bug.sby
rtl/verilog/pfpu32/pfpu32_cmp.v

This adds formal verification for the comparison unit in the FPU. Comparison operations don't appear to be fully specified in the ISA spec, but I took my best stab at sensible semantics, based on my understanding of IEEE 754.
For the most part, what I came up with lines up with the implementation. The only difference is the behaviour of `sfult`, `sfule`, `sfugt`, and `sfuge` when given a signalling NaN. I believe these should result in an exception (signalled by `inv_o`), but the implementation doesn't do this.
To get tests to pass, the assertions introduced here have an exception carved out for this behavioural difference. This exception is disabled in the `pfpu32_cmp_snan_bug` test, which currently fails.

Formal verification for pfpu32_cmp

---

bench/formal/Makefile
bench/formal/f_multiclock_pfpu32_op.v
bench/formal/pfpu32_addsub.sby
bench/formal/pfpu32_muldiv.sby
bench/formal/pfpu32_muldiv_check.sby
rtl/verilog/pfpu32/pfpu32_addsub.v
rtl/verilog/pfpu32/pfpu32_muldiv.v

This adds formal verification for the multiplication outputs in pfpu32_muldiv, and some division outputs too.
To achieve this, I assumed (but not yet verified) that the muldiv module will not receive further requests for the 12 cycles following a division request, since the module will be busy with the Goldschmidt algorithm.
To make verification of the multiplication output tractable, I've split it into two pieces. The `pfpu_muldiv_check` target in the Makefile checks a series of assertions that together imply an assumption in the `pfpu_muldiv` target. Unfortunately, making the first set of assertions isn't enough to guide the solver towards proving the assumption within a reasonable amount of time.
~I also had to fix a couple of bugs: 5ba34a3.~

Formal verification for pfpu32_muldiv: MULT (and some DIV)
